### ISSUE TITLE
Stamina system

### ISSUE THREAD

**Issue by DamienAmbrose** [Default-Cube-Studios/Movement-Template#2]
A system that can regenerate the player's stamina and reduce it while it is moving, jumping, et cetera, and provides a visual indicator. 

### Planned features:
- [x] Stamina loss while moving, jumping, sprinting
- [x] Stamina regen while idle
- [x] Decreased movement speed while no stamina
- [x] Decreased jump while no stamina
- [x] No sprint while no stamina

**Comment by DamienAmbrose** [comment]
Here's the final build of the stamina system as of the merger from the `Feature-Update` branch
[x86.zip](https://github.com/Default-Cube-Studios/Movement-Template/files/10146819/x86.zip)

**Comment by adityamallkush** [comment]
This is the latest version as on December 6th 2022.
[x86.zip](https://github.com/Default-Cube-Studios/Movement-Template/files/10166959/x86.zip)
